FROM rust:1.94-alpine

RUN apk add --no-cache \
    bash \
    ca-certificates \
    openssl-dev \
    mysql-client \
    mysql-dev \
    build-base \
    pkgconfig \
    musl-dev \
    linux-headers

RUN cargo install cargo-watch

WORKDIR /usr/src/app

EXPOSE 3004
CMD ["cargo", "watch", "-x", "run"]
